export const LOGIN_AUTH_REQUEST = 'LOGIN_AUTH_REQUEST';
export const LOGIN_AUTH_SUCESS = 'LOGIN_AUTH_SUCESS';
export const LOGIN_AUTH_FAILED = 'LOGIN_AUTH_FAILED';

export const LOGOUT_AUTHENTICATION = 'LOGOUT_AUTHENTICATION';

export const GET_AUTH_PROFILE_REQUEST = 'GET_AUTH_PROFILE_REQUEST';
export const GET_AUTH_PROFILE_SUCESS = 'GET_AUTH_PROFILE_SUCESS';
export const GET_AUTH_PROFILE_FAILED = 'GET_AUTH_PROFILE_FAILED';

export const REDIRECT = "REDIRECT";