export const LOGIN_AUTH_REQUEST = 'LOGIN_AUTH_REQUEST';
export const LOGIN_AUTH_SUCESS = 'LOGIN_AUTH_SUCESS';
export const LOGIN_AUTH_FAILED = 'LOGIN_AUTH_FAILED';

export const LOGOUT_AUTHENTICATION = 'LOGOUT_AUTHENTICATION';